const cardData = {
    "categories": [
        {
            "name": "Startup Spirits",
            "color": "#8E44AD",
            "questions": [
                "What's the most innovative startup you've encountered recently?",
                "If you could solve any global problem with technology, what would it be and how?",
                "Describe a time when you had to think \"outside the box\" to solve a problem.",
                "What emerging technology excites you the most and why?",
                "If you could instantly become an expert in one area of technology, what would it be?",
                "What's a common product or service that you think is due for disruption?",
                "Describe your ideal brainstorming environment.",
                "What's the most creative use of AI you've seen or can imagine?",
                "If you could combine two existing technologies to create something new, what would they be?",
                "What's a low-tech solution you've seen that impressed you with its innovation?",
                "How do you stay creative and generate new ideas?",
                "What's the most unusual source of inspiration you've had for an idea?",
                "If you could design a new feature for your smartphone, what would it be?",
                "What's a product or service you wish existed but doesn't yet?",
                "How do you think virtual or augmented reality could be used in everyday life?",
                "What's the most interesting startup idea you've heard recently?",
                "If you could automate one aspect of your daily life, what would it be?",
                "What's a technology from science fiction that you'd love to see become reality?",
                "How do you think blockchain could be used beyond cryptocurrency?",
                "What's an industry you think is ripe for technological innovation?"
            ]
        },
        {
            "name": "Aged Ambitions",
            "color": "#2980B9",
            "questions": [
                "If your career was a wine, how would you describe its 'tasting notes'?",
                "What's the best career advice you've ever received?",
                "Describe a skill you're currently working on improving. Why did you choose it?",
                "If you could switch careers to any field, what would it be and why?",
                "What's a personal or professional goal you're working towards this year?",
                "Describe a failure that ultimately led to a valuable lesson or opportunity.",
                "What's the most challenging aspect of your current role, and how are you addressing it?",
                "If you could have dinner with any tech leader, who would it be and what would you ask them?",
                "What's a book, podcast, or resource that has significantly impacted your career?",
                "How do you stay up-to-date with industry trends and developments?",
                "Describe a time when you had to adapt to a major change in your work environment.",
                "What's a soft skill you think is undervalued in the tech industry?",
                "If you could go back in time and give advice to your younger self starting in tech, what would it be?",
                "What's the most valuable lesson you've learned from a colleague or mentor?",
                "How do you balance specialization with being a generalist in your field?",
                "What's a project or achievement you're particularly proud of?",
                "How do you approach networking in the tech industry?",
                "What's a skill outside your core expertise that you'd like to develop?",
                "Describe your ideal work environment and culture.",
                "How do you handle imposter syndrome in a fast-paced tech environment?",
                "What's the biggest risk you've taken in your career, and was it worth it?"
            ]
        },
        {
            "name": "Future Flavors",
            "color": "#16A085",
            "questions": [
                "What technology do you think will have the biggest impact in the next 5 years?",
                "How do you think AI will change the job market in the coming decade?",
                "What's your take on the future of remote work and digital nomadism?",
                "How do you envision the role of quantum computing in the future?",
                "What are your thoughts on the metaverse and its potential applications?",
                "How do you think renewable energy technologies will evolve in the next 10 years?",
                "What's your opinion on the future of transportation (e.g., autonomous vehicles, hyperloop)?",
                "How do you think biotechnology will impact our lives in the coming years?",
                "What are your thoughts on the future of education and online learning?",
                "How do you think cybersecurity challenges will evolve with advancing technology?",
                "What's your vision for the future of social media and online communication?",
                "How do you think 3D printing technology will impact manufacturing and consumerism?",
                "What role do you think space technology will play in our everyday lives in the future?",
                "How do you envision the future of human-computer interaction?",
                "What are your thoughts on the potential and challenges of gene editing technologies?",
                "How do you think IoT (Internet of Things) will shape our homes and cities in the future?",
                "What's your take on the future of digital privacy and data ownership?",
                "How do you think augmented reality will be used in professional settings?",
                "What are your thoughts on the future of digital currencies and decentralized finance?",
                "How do you envision technology changing healthcare in the coming decades?"
            ]
        },
        {
            "name": "Entrepreneurial Elixirs",
            "color": "#C0392B",
            "questions": [
                "What's the biggest challenge you've faced in your entrepreneurial journey?",
                "If you could start a company in any industry, what would it be and why?",
                "What's a common misconception about startups that you'd like to debunk?",
                "How do you approach fundraising and investor relationships?",
                "What's your strategy for building and managing a team in a startup environment?",
                "How do you balance innovation with profitability in a startup?",
                "What's your approach to customer discovery and product-market fit?",
                "How do you handle competition in a rapidly evolving market?",
                "What's your take on the importance of company culture in startups?",
                "How do you approach scaling a business while maintaining quality?",
                "What's a key lesson you've learned about time management as an entrepreneur?",
                "How do you approach pivoting when your original idea isn't working?",
                "What's your strategy for marketing a tech product or service?",
                "How do you balance long-term vision with short-term goals in a startup?",
                "What's your approach to pricing strategies for tech products or services?",
                "How do you handle the uncertainty and risk inherent in startups?",
                "What's your take on the importance of networking in the startup ecosystem?",
                "How do you approach partnerships and collaborations in the tech industry?",
                "What's your strategy for staying ahead of market trends?",
                "How do you measure success in a startup beyond financial metrics?"
            ]
        },
        {
            "name": "Balanced Blend",
            "color": "#F39C12",
            "questions": [
                "How do you maintain work-life balance in a fast-paced tech environment?",
                "What's your favorite way to unwind after a long day of coding or meetings?",
                "How do you stay physically active with a desk-bound job?",
                "What's your approach to managing stress in a high-pressure startup environment?",
                "How do you nurture your creative side outside of work?",
                "What's a hobby or interest you have that might surprise your colleagues?",
                "How do you handle burnout, and what are your strategies for prevention?",
                "What's your ideal workweek structure for optimal productivity and wellbeing?",
                "How do you maintain social connections in a potentially isolating tech career?",
                "What's your approach to continuous learning without overwhelming yourself?",
                "How do you create boundaries between work and personal life, especially when working remotely?",
                "What's a personal ritual or habit that significantly improves your day?",
                "How do you approach mindfulness or meditation in relation to your work?",
                "What's your strategy for maintaining healthy eating habits with a busy schedule?",
                "How do you ensure you get enough quality sleep with potentially irregular work hours?",
                "What's your approach to taking vacations or extended breaks from work?",
                "How do you cultivate non-tech related skills or interests?",
                "What's your strategy for staying motivated during long-term projects?",
                "How do you maintain a healthy relationship with technology outside of work?",
                "What's your approach to creating a comfortable and productive home office environment?"
            ]
        }
    ]
}